// Vendor the proof-verification + receipt browser modules from @infrix/verify
// (the canonical SDK-side verifier closure) into ./vendor. @infrix/verify is the
// single source of truth for the SDKs (it in turn vendors from pkg/nexus/web and
// is drift-fenced against it); vendoring from the sibling package — rather than
// reaching into pkg/nexus/web — keeps this package self-contained and buildable
// outside the monorepo (Tier-1 SDK extraction). Regenerated by `npm run build`;
// never hand-edit ./vendor.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const verifySrc = path.resolve(pkgRoot, '..', 'verify', 'src'); // @infrix/verify (workspace sibling)

// The dependency closure for verifyPortablePackage + the receipt component.
// These already carry package-relative imports (rewritten by @infrix/verify).
const FILES = [
  'canonicalJson.js',
  'portableVerifier.js',
  'proofReceipt.js',
  'proofReceiptView.js',
];

if (!fs.existsSync(verifySrc)) {
  console.error(`vendor: @infrix/verify source not found at ${verifySrc} — is the workspace sibling present?`);
  process.exit(1);
}

const outDir = path.join(pkgRoot, 'vendor');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const f of FILES) {
  const abs = path.join(verifySrc, f);
  if (!fs.existsSync(abs)) {
    console.error(`vendor: missing ${f} in @infrix/verify (${verifySrc})`);
    process.exit(1);
  }
  fs.copyFileSync(abs, path.join(outDir, f));
}

console.log(`@infrix/proof-receipt: vendored ${FILES.length} module(s) from @infrix/verify into vendor/`);
