// Vendor the canonical proof-verification + receipt browser modules from
// pkg/nexus/web into ./vendor (adoption-10). The single source of truth stays
// in pkg/nexus/web; this copy is regenerated by `npm run build` and rewrites
// the SPA's absolute `/lib` and `/components` imports to package-relative paths
// so the package is self-contained. Never hand-edit ./vendor.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const repoRoot = path.resolve(pkgRoot, '..', '..', '..'); // sdk/packages/proof-receipt -> repo root
const webRoot = path.join(repoRoot, 'pkg', 'nexus', 'web');

// The dependency closure for verifyPortablePackage + the receipt component.
const FILES = [
  'lib/canonicalJson.js',
  'lib/portableVerifier.js',
  'lib/proofReceipt.js',
  'components/proofReceiptView.js',
];

const HEADER = '// VENDORED from pkg/nexus/web — generated by scripts/vendor.mjs. Do not edit.\n';
const rewrite = (src) => src.replace(/from\s+'\/(?:lib|components)\/([^']+)'/g, "from './$1'");

const outDir = path.join(pkgRoot, 'vendor');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const rel of FILES) {
  const abs = path.join(webRoot, rel);
  if (!fs.existsSync(abs)) {
    console.error(`vendor: missing source ${rel} (looked in ${webRoot})`);
    process.exit(1);
  }
  const src = fs.readFileSync(abs, 'utf8');
  fs.writeFileSync(path.join(outDir, path.basename(rel)), HEADER + rewrite(src));
}

console.log(`@infrix/proof-receipt: vendored ${FILES.length} module(s) into vendor/`);
