// @infrix/widgets — UX label fixture drift test (nextux-09).
//
// The widgets MUST render with the SAME assurance badges, error cards, glossary,
// and trust-boundary labels Nexus and the SDK use — no duplicate wording. This
// proves the fixture the widget bundles is byte-identical to the canonical
// fixture (generated by pkg/uxcopy, consumed by Nexus). If the canonical fixture
// changes, rebuild the package (`npm run build`) to re-vendor it.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// The bundled fixture the widget actually renders from.
import bundled from '../vendor/uxFixture.js';

const here = dirname(fileURLToPath(import.meta.url)); // test-dist/test
const repoRoot = join(here, '..', '..', '..', '..', '..');

test('the bundled UX label fixture matches the canonical Nexus fixture (no duplicate wording)', () => {
  const canonical = JSON.parse(
    readFileSync(join(repoRoot, 'pkg', 'nexus', 'web', 'testdata', 'uxcopy.fixture.json'), 'utf8'),
  );
  assert.deepEqual(bundled, canonical, 'widgets must consume the canonical UX label fixture verbatim');
});

test('the canonical assurance badges are data-gated (a green badge needs a condition)', () => {
  const fixture = bundled as unknown as { assuranceBadges: Array<{ colorRole?: string; allowedConditions?: string[] }> };
  for (const b of fixture.assuranceBadges) {
    if (b.colorRole === 'positive') {
      assert.ok((b.allowedConditions || []).length > 0, 'a positive badge must require at least one condition');
    }
  }
});
