// Vendor the canonical proof-verification + UX-label browser modules from
// pkg/nexus/web into src/vendor (nextux-09). The single source of truth stays in
// pkg/nexus/web (and pkg/uxcopy for the label fixture); this copy is regenerated
// by `npm run build` and rewrites the SPA's absolute `/lib` imports to
// package-relative paths so the package is self-contained. Never hand-edit
// src/vendor — it is generated.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const repoRoot = path.resolve(pkgRoot, '..', '..', '..'); // sdk/packages/widgets -> repo root
const webRoot = path.join(repoRoot, 'pkg', 'nexus', 'web');

// The dependency closure for in-browser verification + the canonical labels.
const LIB_FILES = [
  'lib/canonicalJson.js',
  'lib/portableVerifier.js',
  'lib/proofReceipt.js',
  'lib/proofStory.js',
  'lib/uxLabels.js',
];

// The canonical UX label fixture (assurance badges, error cards, glossary,
// trust-boundary labels) — the SAME fixture Nexus + the SDK consume, so the
// widgets never duplicate wording.
const FIXTURE = 'testdata/uxcopy.fixture.json';

const HEADER = '// VENDORED from pkg/nexus/web — generated by scripts/vendor.mjs. Do not edit.\n';
const rewrite = (src) => src.replace(/from\s+'\/(?:lib|components)\/([^']+)'/g, "from './$1'");

const outDir = path.join(pkgRoot, 'src', 'vendor');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const rel of LIB_FILES) {
  const abs = path.join(webRoot, rel);
  if (!fs.existsSync(abs)) {
    console.error(`vendor: missing source ${rel} (looked in ${webRoot})`);
    process.exit(1);
  }
  fs.writeFileSync(path.join(outDir, path.basename(rel)), HEADER + rewrite(fs.readFileSync(abs, 'utf8')));
}

// Inline the label fixture as a TS module so it is bundled into dist (tsc does
// not copy raw .json to the output). It stays byte-identical to the canonical
// fixture — the drift test compares them.
const fixtureAbs = path.join(webRoot, FIXTURE);
if (!fs.existsSync(fixtureAbs)) {
  console.error(`vendor: missing label fixture ${FIXTURE}`);
  process.exit(1);
}
const fixtureRaw = fs.readFileSync(fixtureAbs, 'utf8');
// Keep a verbatim copy for the drift test, and a TS module for the bundle.
fs.writeFileSync(path.join(outDir, 'uxcopy.fixture.json'), fixtureRaw);
fs.writeFileSync(
  path.join(outDir, 'uxFixture.ts'),
  HEADER + '/* eslint-disable */\nexport default ' + JSON.stringify(JSON.parse(fixtureRaw)) + ' as const;\n',
);

console.log(`@infrix/widgets: vendored ${LIB_FILES.length} module(s) + the UX label fixture into src/vendor/`);
