// Vendor the proof-verification + UX-label browser modules and the canonical UX
// label fixture from @infrix/verify (the SDK-side verifier closure) into
// src/vendor (nextux-09). @infrix/verify is the single source of truth for the
// SDKs (it vendors from pkg/nexus/web + pkg/uxcopy and is drift-fenced against
// them); vendoring from the sibling package keeps @infrix/widgets self-contained
// and buildable outside the monorepo (Tier-1 SDK extraction). Regenerated by
// `npm run build`; never hand-edit src/vendor.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const verifySrc = path.resolve(pkgRoot, '..', 'verify', 'src'); // @infrix/verify (workspace sibling)

// The dependency closure for in-browser verification + the canonical labels.
// These already carry package-relative imports (rewritten by @infrix/verify).
const LIB_FILES = [
  'canonicalJson.js',
  'portableVerifier.js',
  'proofReceipt.js',
  'proofStory.js',
  'uxLabels.js',
];

const HEADER = '// VENDORED from @infrix/verify — generated by scripts/vendor.mjs. Do not edit.\n';

if (!fs.existsSync(verifySrc)) {
  console.error(`vendor: @infrix/verify source not found at ${verifySrc} — is the workspace sibling present?`);
  process.exit(1);
}

const outDir = path.join(pkgRoot, 'src', 'vendor');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const f of LIB_FILES) {
  const abs = path.join(verifySrc, f);
  if (!fs.existsSync(abs)) {
    console.error(`vendor: missing ${f} in @infrix/verify (${verifySrc})`);
    process.exit(1);
  }
  fs.copyFileSync(abs, path.join(outDir, f));
}

// The UX label fixture (assurance badges, error cards, glossary, trust-boundary
// labels). Keep a verbatim copy for the drift test, and inline it as a TS module
// so it is bundled into dist (tsc does not copy raw .json to the output).
const fixtureRaw = fs.readFileSync(path.join(verifySrc, 'uxcopy.fixture.json'), 'utf8');
fs.writeFileSync(path.join(outDir, 'uxcopy.fixture.json'), fixtureRaw);
fs.writeFileSync(
  path.join(outDir, 'uxFixture.ts'),
  HEADER + '/* eslint-disable */\nexport default ' + JSON.stringify(JSON.parse(fixtureRaw)) + ' as const;\n',
);

console.log(`@infrix/widgets: vendored ${LIB_FILES.length} module(s) + the UX label fixture from @infrix/verify into src/vendor/`);
